Backend/urls.py
from django.urls import path,include
from Backend.views import index,product_list_view,category_list_view,\
    category_product_list_view,product_detail_view,tag_list,ajax_add_review,\
    search_view,filter_product,add_to_cart,cart_view,delete_item_from_cart,\
    update_cart,checkout_view,payment_completed_view,payment_failed_view,about,contact,contact_save


app_name = "Backend"


urlpatterns=[

    # Homepage
    path("",index, name="index"),

    # Products
    path("products/",product_list_view,name="product_list"),
    path("product/<pid>/",product_detail_view,name="product_detail"),

    # Category
    path("category/",category_list_view,name="category_list"),
    path("category/<cid>/",category_product_list_view,name="category_product_list"),

    # Tags
    path("products/tag/<slug:tag_slug>/",tag_list,name="tags"),

    #Add Review
    path("ajax_add_review/<int:pid>/",ajax_add_review,name="ajax_add_review"),

    #Search
    path("search/",search_view,name="search"),

    #Filter Products
    path("filter-products/",filter_product,name="filter-product"),

    #Add to cart
    path("add-to-cart/", add_to_cart, name="add-to-cart"),

    #Cart Page
    path("cart/", cart_view, name="cart"),

    #Delete item from cart
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    #Update Cart
    path("update-cart/", update_cart, name="update-cart"),

    #Checkout
    path("checkout/", checkout_view, name="checkout"),


    #Payment Successful
    path("payment-completed/", payment_completed_view, name="payment-completed"),

    #Payment Failed
    path("payment-failed/", payment_failed_view, name="payment-failed"),


    #Wishlist Page
    # path("wishlist/", wishlist_view, name="wishlist"),

    #Adding to wishlist
    # path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),

    # path("invoice_view/", invoice_view, name="invoice_view"),


    #About
    path("about/", about, name="about"),

    #Contact
    path("contact/", contact, name="contact"),
    path('contact_save/', contact_save, name='contact_save'),





]

Coza_Store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Backend.urls")),
    path("user/",include("userauthentication.urls", namespace='userauthentication')),

    # path("ckeditor/", include("ckeditor_uploader.urls")),



]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Backend/forms.py
from django import forms
from Backend.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"Write Review"}))


    class Meta:
        model = ProductReview
        fields = ['review','rating']

Backend/views.py
# Create your views here.
from django.shortcuts import render,get_object_or_404,redirect
from django.http import JsonResponse
from taggit.models import Tag
from django.db.models import Avg
from Backend.models import Product,Category,Vendor,CartOrder,CartOrderItems,ProductImages,wishlist_model,ProductReview,Address,ContactUs
from Backend.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages
import razorpay
from django.conf import settings
from django.http import HttpResponse
from xhtml2pdf import pisa
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required




# Create your views here.

def index(request):
    # products = Product.objects.all().order_by("-id")                                    #Filter query
    products = Product.objects.filter( featured=True)
    context = {
        "products":products
    }
    return render(request, 'backend/index.html',context)


def product_list_view(request):
    products = Product.objects.filter(featured=True)
    context = {
        "products": products
    }
    return render(request, 'backend/product_list.html', context)


def category_list_view(request):
    categories = Category.objects.all()
    context = {
        "categories": categories
    }
    return render(request, 'backend/category_list.html', context)


def category_product_list_view(request,cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(featured=True,category=category)

    context = {
        "category":category,
        "products":products,


    }
    return render(request,"Backend/category_product_list.html", context)


def product_detail_view(request,pid):
    product = Product.objects.get(pid=pid)

    p_image = product.p_image.all()
    size = [choice[1] for choice in product._meta.get_field('size').choices]
    color = [choice[1] for choice in product._meta.get_field('color').choices]
    products = Product.objects.filter(category=product.category).exclude(pid=pid)

    # Getting all reviews
    reviews = ProductReview.objects.filter(product=product).order_by("-date")
   # Getting average reviews
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    #Product Review Form

    review_form = ProductReviewForm()

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user,product=product).count()
        if user_review_count>0:
            make_review = False


    context = {
        "p":product,
        "p_image":p_image,
        "size":size,
        "color":color,
        "products":products,
        "reviews":reviews,
        "average_rating":average_rating,
        "review_form":review_form,
        "make_review":make_review,

    }

    return render(request,"Backend/product_detail.html", context)


def tag_list(request, tag_slug=None):
    products = Product.objects.filter(featured=True).order_by("-id")
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

        context = {
            'products':products,
        }

        return render(request,"Backend/tag.html", context)


def ajax_add_review(request,pid):
    product = Product.objects.get(pk=pid)
    user = request.user

    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST['review'],
        rating = request.POST['rating'],


    )

    context = {
        'user':user.username,
        'review' : request.POST['review'],
        'rating' : request.POST['rating'],
        }


    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))
    return JsonResponse(
        {
            'bool': True,
         'context': context,
         'average_reviews': average_reviews,
        }

    )


def search_view(request):
    query = request.GET.get("q")
    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        'products':products,
        'query':query,
    }

    return render(request, 'backend/search.html', context)


def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(featured=True).order_by("-id").distinct()

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)


    if len(categories)>0:
        products = products.filter(category__id__in=categories).distinct()


    if len(vendors)>0:
        products = products.filter(vendor__id__in=vendors).distinct()

    data = render_to_string("backend/async/product_list.html", {"products":products})

    return JsonResponse({"data":data})


def add_to_cart(request):
    cart_product = {}
    cart_product[str(request.GET['id'])] = {
        'title':request.GET['title'],
        'qty':request.GET['qty'],
        'price':request.GET['price'],
        'image':request.GET['image'],
        'pid':request.GET['pid'],

    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj']  = cart_product

    return JsonResponse({"data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})


def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            try:
                qty = int(item.get('qty', 0))
                price = float(item.get('price', 0))
                cart_total_amount += qty * price
            except ValueError:
                # Handle the case where qty or price are not valid numbers
                messages.error(request, f"Invalid data for product ID {p_id}.")
                continue

        return render(request, "Backend/cart.html", {
            "cart_data": request.session['cart_data_obj'],
            'totalcartitems': len(request.session['cart_data_obj']),
            'cart_total_amount': cart_total_amount
        })
    else:
        messages.warning(request, "Your Cart is Empty")
        return redirect("Backend:index")


def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

    context = render_to_string("backend/async/cart_list.html",{"cart_data": request.session['cart_data_obj'],
                                                   'totalcartitems': len(request.session['cart_data_obj']),
                                                   'cart_total_amount':cart_total_amount})
    return JsonResponse({"data":context, 'totalcartitems': len(request.session['cart_data_obj'])})


def update_cart(request):
    product_id = str(request.GET['id'])
    product_qty = request.GET['qty']
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = product_qty
            request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

    context = render_to_string("backend/async/cart_list.html",{"cart_data": request.session['cart_data_obj'],
                                                   'totalcartitems': len(request.session['cart_data_obj']),
                                                   'cart_total_amount':cart_total_amount})
    return JsonResponse({"data":context, 'totalcartitems': len(request.session['cart_data_obj'])})




@login_required
def checkout_view(request):
    cart_total_amount = 0
    total_amount = 0
    if 'cart_data_obj' in request.session:

        #Getting total amount for the cart
        for p_id, item in request.session['cart_data_obj'].items():
            total_amount += int(item['qty']) * float(item['price'])

        #Create order objects
        order = CartOrder.objects.create(
            user = request.user,
            price = total_amount
        )
        #Getting total amount for the cart
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

            cart_order_products = CartOrderItems.objects.create(
                order = order,
                invoice_no = "INVOICE_NO-" + str(order.id),
                item = item['title'],
                image = item['image'],
                qty = item['qty'],
                price = item['price'],
                total = float(item['qty']) * float(item['price'])
            )





    cart_total_amount = 0

templates/Backend/cart.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

	<main id="cart-list">
		<!-- Cart -->
	<div class="wrap-header-cart js-panel-cart">
		<div class="s-full js-hide-cart"></div>

		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Your Cart
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>

			<div class="header-cart-content flex-w js-pscroll">
				<ul class="header-cart-wrapitem w-full">
					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'assets/images/item-cart-01.jpg'%}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								White Shirt Pleat
							</a>

							<span class="header-cart-item-info">
								1 x $19.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'assets/images/item-cart-02.jpg'%}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Converse All Star
							</a>

							<span class="header-cart-item-info">
								1 x $39.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'assets/images/item-cart-03.jpg'%}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Nixon Porter Leather
							</a>

							<span class="header-cart-item-info">
								1 x $17.00
							</span>
						</div>
					</li>
				</ul>

				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						Total: $75.00
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a>

						<a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb  p-l-25 p-r-15 p-t-30 p-lr-0-lg">
<!--			<a href="index.html" class="stext-109 cl8 hov-cl1 trans-04">-->
<!--				Home-->
<!--				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>-->
<!--			</a>-->

<!--			<span class="stext-109 cl4">-->
<!--				Shoping Cart-->
<!--			</span>-->
		</div>
	</div>


	<!-- Shoping Cart -->
	<form class="bg0 p-t-75 p-b-85">
		<h6 style="margin-left:175px;" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">There are <span>{{ totalcartitems}}</span> products in your cart</h6><br>
		<div class="container" >
			<div class="row">
				<div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
					<div class="m-l-25 m-r--38 m-lr-0-xl">
						<div class="wrap-table-shopping-cart" style="width:800px;">
							<table class="table-shopping-cart" >
								<tr class="table_head">
									<th class="column-1">
										<input class="form-check-input" type="checkbox" id="exampleCheckbox11">
										<label class="form-check-label" for="examplecheckbox11"></label>
									</th>
									<th class="column-2" style="width:70px;">Product</th>
									<th class="column-3" style="width:70px;">Title</th>
									<th class="column-4" style="width:70px;">Price</th>
									<th class="column-5" style="width:70px;">Quantity</th>
									<th class="column-6" style="width:70px;">Total</th>
									<th class="column-7" style="width:70px;">Refresh</th>
									<th class="column-8" style="width:100px;">Remove</th>
								</tr>

								{% for product_id, item in cart_data.items %}
								<tr class="table_row">
									<td class="column-1">
										<input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1">
										<label class="form-check-label" for="exampleCheckbox1"></label>

									</td>
									<td class="column-2">
										<div class="how-itemcart1">
											<img src="{{item.image}}" alt="IMG">
										</div>
									</td>
									<td class="column-3">
										<h6>
											<a href="{% url 'Backend:product_detail' item.pid %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">{{item.title}}</a>
										</h6>
									</td>
									<td class="column-4">₹ {{item.price|floatformat:2}}</td>
									<td class="column-5">
										<div class="wrap-num-product flex-w m-l-auto m-r-0" style="width:70px;">
											<input type="number" placeholder="Qty"  class="product-qty-{{ product_id }}" value="{{item.qty}}"  >
										</div>
									</td>
									<td class="column-6">₹ {% widthratio item.price 1 item.qty %}</td>
<!--									<td class="column-7"><a class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6 update-product" data-product="{{ product_id }}"><i class="fa-solid fa-arrows-rotate" style="font-size:18px;"></i></a></td>-->
									<td class="column-8" data-title="Refresh"><button class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6 update-product" data-product="{{ product_id }}"><i class="fa-solid fa-arrows-rotate" style="font-size:18px;margin-left:20px;"></i></button></td>
									<td class="column-8" data-title="Remove"><button class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6 delete-product" data-product="{{ product_id }}"><i class="fa-regular fa-trash-can" style="font-size:18px;margin-left:20px;"></i></button></td>
								</tr>
								{% endfor %}









<!--								<tr class="table_row">-->
<!--									<td class="column-1">-->
<!--										<div class="how-itemcart1">-->
<!--											<img src="{% static 'assets/images/item-cart-05.jpg'%}" alt="IMG">-->
<!--										</div>-->
<!--									</td>-->
<!--									<td class="column-2">Lightweight Jacket</td>-->
<!--									<td class="column-3">$ 16.00</td>-->
<!--									<td class="column-4">-->
<!--										<div class="wrap-num-product flex-w m-l-auto m-r-0">-->
<!--											<div class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">-->
<!--												<i class="fs-16 zmdi zmdi-minus"></i>-->
<!--											</div>-->

<!--											<input class="mtext-104 cl3 txt-center num-product" type="number" name="num-product2" value="1">-->

<!--											<div class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m">-->
<!--												<i class="fs-16 zmdi zmdi-plus"></i>-->
<!--											</div>-->
<!--										</div>-->
<!--									</td>-->
<!--									<td class="column-5">$ 16.00</td>-->
<!--								</tr>-->


							</table>
						</div>

						<div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
							<div class="flex-w flex-m m-r-20 m-tb-5">
<!--								<input class="stext-104 cl2 plh4 size-117 bor13 p-lr-20 m-r-10 m-tb-5" type="text" name="coupon" placeholder="Coupon Code">-->

<!--								<div class="flex-c-m stext-101 cl2 size-118 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-5">-->
<!--									Apply coupon-->
<!--								</div>-->
							</div>

<!--							<div class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10">-->
<!--								Update Cart-->
<!--							</div>-->
						</div>
					</div>
				</div>

				<div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
					<div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm" style="margin-left:200px; width:350px;">
						<h4 class="mtext-109 cl2 p-b-30">
							Cart Totals
						</h4>

						<div class="flex-w flex-t bor12 p-b-13">
							<div class="size-208">
								<span class="stext-110 cl2">
									Subtotal:
								</span>
							</div>

							<div class="size-209">
								<span class="mtext-110 cl2">
									₹{{cart_total_amount | floatformat:2}}
								</span>
							</div>
						</div>

						<div class="flex-w flex-t bor12 p-t-15 p-b-30">
							<div class="size-208 w-full-ssm">
								<span class="stext-110 cl2">
									Shipping:
								</span>
							</div>

							<div class="size-209 p-r-18 p-r-0-sm w-full-ssm">
								<p class="stext-111 cl6 p-t-2">
									There are no shipping methods available. Please double check your address, or contact us if you need any help.
								</p>

								<div class="p-t-15">

<!--									<div class="rs1-select2 rs2-select2 bor8 bg0 m-b-12 m-t-9">-->
<!--										<select class="js-select2" name="time">-->
<!--											<option>Select a country...</option>-->
<!--											<option>USA</option>-->
<!--											<option>UK</option>-->
<!--										</select>-->
<!--										<div class="dropDownSelect2"></div>-->
<!--									</div>-->

									<div class="bor8 bg0 m-b-12" style="border:1px solid grey width:400px;height:50px;margin-left:-90px;padding-top:15px;" >
										<span style="float:right:" class="stext-110 cl2">Shipping</span><span style="float:right;" class="stext-110 cl2">Free</span>
									</div>

<!--									<div class="bor8 bg0 m-b-22">-->
<!--										<input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="postcode" placeholder="Postcode / Zip">-->
<!--									</div>-->

									<div class="flex-w">
										<div class="flex-c-m stext-101 cl2 size-115 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer">
											Update Totals
										</div>
									</div>

								</div>
							</div>
						</div>

						<div class="flex-w flex-t p-t-27 p-b-33">
							<div class="size-208">
								<span class="mtext-101 cl2">
									Total:
								</span>
							</div>

							<div class="size-209 p-t-1">
								<span class="mtext-110 cl2">
									₹{{cart_total_amount | floatformat:2}}
								</span>
							</div>
						</div>


						{% if totalcartitems %}
						<button class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer" id="rzp-button1">
							<a href="{% url 'Backend:checkout'  %}" style="color:white;">Proceed to Checkout</a>
						</button>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</form>
	</main>





{% endblock content %}

templates/Backend/payment_completed.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/invoice.css' %}">

</head>
<body>

    <div style="border:1px solid grey;">
    <header class="clearfix">
        <div id="logo">
            <img src="{% static 'assets/images/icons/logo-01.png'%}" style="margin-top:50px;width:130px;height:30px;" alt="CozaStore">
        </div>
        <h1 style="margin-top:50px;">INVOICE 3-2-1</h1>
        <div id="project" style="margin-top:20px;">
            <div><span>INVOICE TO:</span>{{request.user|title}}</div>
        </div>
    </header>
    <main>
        <table style="margin-top:30px;">
            <thead>
                <tr>
                    <th class="service">TITLE</th>
                    <th style="text-align:center;">PRICE</th>
                    <th style="text-align:center;">QTY</th>
                    <th style="text-align:center;">AMOUNT</th>
                </tr>
            </thead>
            <tbody>
                {% for product_id, item in cart_data.items %}
                <tr>
                    <td class="service">{{item.title}}</td>
                    <td class="unit" style="text-align:center;">₹{{item.price}}</td>
                    <td class="qty" style="text-align:center;">{{item.qty}}</td>
                    <td style="text-align:center;">₹{% widthratio item.price 1 item.qty %}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="4">SUBTOTAL</td>
                    <td class="total">{{cart_total_amount}}</td>
                </tr>
                <tr>
                    <td colspan="4" class="grand total"><b>GRAND TOTAL</b></td>
                    <td class="grand total"><b>₹{{cart_total_amount}}</b></td>
                </tr>
            </tbody>
        </table>
    </main>
    <footer>
        Hey {{request.user|title}}, Thank you for Shopping with us
    </footer>
</div>

<div style="margin-top:30px;">
    <button class="btn1 ">
        <a href="{% url 'Backend:payment-completed' %}?download_pdf=1" style="text-decoration:None;color:white">DOWNLOAD</a>
    </button>
    <button class="btn1" ><a href="" style="color:white;text-decoration:None;">PRINT</a></button>
</div>



</body>
</html>

templates/Backend/payment_failed.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}


<div class="div1" style="">

    <div class="div2">
        <h1 class="mtext-105 cl2 js-name-detail p-b-14"><b>Payment Failed!</b></h1>
    <h4 class="mtext-105 cl2 js-name-detail p-b-14">Oops! Something went wrong</h4>
    <h5 class="mtext-106 cl2 " style="color:#bbbfbc;">While trying to reserve money from your account</h5><br>
            <button class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04" style="margin-left:660px;">Try Again</button>

    </div>

</div>

<style>
.div1{
margin-top:100px;
height:100px;
margin-bottom:470px;
text-align:center;
padding-top:100px;

}

.div2{

}
</style>

{% endblock content %}