Backend/urls.py
from django.urls import path,include
from Backend.views import index,product_list_view,category_list_view,\
    category_product_list_view,product_detail_view,tag_list,ajax_add_review,\
    search_view,filter_product,add_to_cart,cart_view,delete_item_from_cart,\
    update_cart,checkout_view,payment_completed_view,payment_failed_view,about,contact,contact_save


app_name = "Backend"


urlpatterns=[

    # Homepage
    path("",index, name="index"),

    # Products
    path("products/",product_list_view,name="product_list"),
    path("product/<pid>/",product_detail_view,name="product_detail"),

    # Category
    path("category/",category_list_view,name="category_list"),
    path("category/<cid>/",category_product_list_view,name="category_product_list"),

    # Tags
    path("products/tag/<slug:tag_slug>/",tag_list,name="tags"),

    #Add Review
    path("ajax_add_review/<int:pid>/",ajax_add_review,name="ajax_add_review"),

    #Search
    path("search/",search_view,name="search"),

    #Filter Products
    path("filter-products/",filter_product,name="filter-product"),

    #Add to cart
    path("add-to-cart/", add_to_cart, name="add-to-cart"),

    #Cart Page
    path("cart/", cart_view, name="cart"),

    #Delete item from cart
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    #Update Cart
    path("update-cart/", update_cart, name="update-cart"),

    #Checkout
    path("checkout/", checkout_view, name="checkout"),


    #Payment Successful
    path("payment-completed/", payment_completed_view, name="payment-completed"),

    #Payment Failed
    path("payment-failed/", payment_failed_view, name="payment-failed"),


    #Wishlist Page
    # path("wishlist/", wishlist_view, name="wishlist"),

    #Adding to wishlist
    # path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),

    # path("invoice_view/", invoice_view, name="invoice_view"),


    #About
    path("about/", about, name="about"),

    #Contact
    path("contact/", contact, name="contact"),
    path('contact_save/', contact_save, name='contact_save'),





]

Coza_Store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Backend.urls")),
    path("user/",include("userauthentication.urls", namespace='userauthentication')),

    # path("ckeditor/", include("ckeditor_uploader.urls")),



]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

userauthentication/urls.py
from django.urls import path
from userauthentication import views

app_name="userauthentication"

urlpatterns = [
    path("sign_up/",views.register_view,name="sign_up"),
    path("sign_in/",views.login_view,name="sign_in"),
    path("sign_out/",views.logout_view,name="sign_out"),
]

userauthentication/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    email = models.EmailField(unique=True,null=False)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)


    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username

userauthentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauthentication.models import User

class UserRegisterForm(UserCreationForm):
    username=forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Username"}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email"}))
    password1=forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}))
    password2=forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm password"}))

    class Meta:
        model = User
        fields = ['username','email']

userauthentication/views.py
# Create your views here.
from django.shortcuts import render,redirect
from userauthentication.forms import UserRegisterForm
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages   #to display msg to the user
from django.conf import settings     #To connect settings.py
from userauthentication.models import User



# User = settings.AUTH_USER_MODEL   #connected the AUTH_USER_MODEL in settings

# Create your views here.

def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():  #checking if it is valid data or malicious data
            new_user = form.save()
            username = form.cleaned_data.get("username") #grabbing the username
            messages.success(request, f"Hey {username}, Your account was created succesfully ")  #shows a message to super user that user created
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password = form.cleaned_data['password1']
            )
            login(request,new_user)
            return redirect("Backend:index")
    else:
        form = UserRegisterForm()

    context = {
        'form':form
    }
    return render(request,"userauthentication/sign_up.html",context)


def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey.. You are already logged in")
        return redirect("Backend:index")
    if request.method=="POST":
        email=request.POST.get('email')
        password=request.POST.get('password')
        try:                              #To Handle errors
            user=User.objects.get(email=email)           #we use get instead of all because we need the data of only one customer at a time
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "You are Logged In")
                return redirect("Backend:index")
            else:
                messages.warning(request, "User Does Not Exist, Create An Account")
        except:
            messages.warning(request, f"user with {email} does not exist")

        #functionality that automatically log the user if there is actually a user with such email


    return render(request,"userauthentication/sign_in.html")


def logout_view(request):
    logout(request)
    messages.success(request, "You Have Logged Out")

    return redirect("userauthentication:sign_in")

templates/userauthentication/sign_in.html
<!DOCTYPE html>
<!-- Coding By CodingNepal - codingnepalweb.com -->
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Responsive Login and Signup Form </title>
        <!-- CSS -->


        <!-- Boxicons CSS -->
        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

    </head>
    <body>
        <section class="container forms">
            <div class="form login">
                <div class="form-content">
                    <header>Login</header>
                    <form action="{% url 'userauthentication:sign_in' %}" method="POST">
                        {% csrf_token %}
                        <div class="field input-field">
                            <input type="email" placeholder="Email" class="input" name="email">
                        </div>
                        <div class="field input-field">
                            <input type="password" placeholder="Password" class="password" name="password">
                            <i class='bx bx-hide eye-icon'></i>
                        </div>
                        <div class="form-link">
                            <a href="#" class="forgot-pass">Forgot password?</a>
                        </div>
                        <div class="field button-field">
                            <button>Login</button>
                        </div>
                    </form>
                    <div class="form-link">
                        <span>Don't have an account? <a href="{% url 'userauthentication:sign_up' %}" class="">Signup</a></span>
                    </div>
<!--                </div>-->
<!--                <div class="line"></div>-->
<!--                <div class="media-options">-->
<!--                    <a href="#" class="field facebook">-->
<!--                        <i class='bx bxl-facebook facebook-icon'></i>-->
<!--                        <span>Login with Facebook</span>-->
<!--                    </a>-->
<!--                </div>-->
<!--                <div class="media-options">-->
<!--                    <a href="#" class="field google">-->
<!--                        <img src="#" alt="" class="google-img">-->
<!--                        <span>Login with Google</span>-->
<!--                    </a>-->
<!--                </div>-->
            </div>
            </div>
        </section>
        <!-- JavaScript -->

        <style>

*{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
}
.container{
    height: 100vh;
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #d4d4d4;
    column-gap: 30px;
}
.form{
    position: absolute;
    max-width: 430px;
    width: 100%;
    padding: 30px;
    border-radius: 6px;
    background: #FFF;
}
.form.signup{
    opacity: 0;
    pointer-events: none;
}
.forms.show-signup .form.signup{
    opacity: 1;
    pointer-events: auto;
}
.forms.show-signup .form.login{
    opacity: 0;
    pointer-events: none;
}
header{
    font-size: 28px;
    font-weight: 600;
    color: #232836;
    text-align: center;
}
form{
    margin-top: 30px;
}
.form .field{
    position: relative;
    height: 50px;
    width: 100%;
    margin-top: 20px;
    border-radius: 6px;
}
.field input,
.field button{
    height: 100%;
    width: 100%;
    border: none;
    font-size: 16px;
    font-weight: 400;
    border-radius: 6px;
}
.field input{
    outline: none;
    padding: 0 15px;
    border: 1px solid#CACACA;
}
.field input:focus{
    border-bottom-width: 2px;
}
.eye-icon{
    position: absolute;
    top: 50%;
    right: 10px;
    transform: translateY(-50%);
    font-size: 18px;
    color: #8b8b8b;
    cursor: pointer;
    padding: 5px;
}
.field button{
    color: #fff;
    background-color: #0171d3;
    transition: all 0.3s ease;
    cursor: pointer;
}
.field button:hover{
    background-color: #016dcb;
}
.form-link{
    text-align: center;
    margin-top: 10px;
}
.form-link span,
.form-link a{
    font-size: 14px;
    font-weight: 400;
    color: #232836;
}
.form a{
    color: #0171d3;
    text-decoration: none;
}
.form-content a:hover{
    text-decoration: underline;
}
.line{
    position: relative;
    height: 1px;
    width: 100%;
    margin: 36px 0;
    background-color: #d4d4d4;
}
.line::before{
    content: 'Or';
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background-color: #FFF;
    color: #8b8b8b;
    padding: 0 15px;
}
.media-options a{
    display: flex;
    align-items: center;
    justify-content: center;
}
a.facebook{
    color: #fff;
    background-color: #4267b2;
}
a.facebook .facebook-icon{
    height: 28px;
    width: 28px;
    color: #0171d3;
    font-size: 20px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #fff;
}
.facebook-icon,
img.google-img{
    position: absolute;
    top: 50%;
    left: 15px;
    transform: translateY(-50%);
}
img.google-img{
    height: 20px;
    width: 20px;
    object-fit: cover;
}
a.google{
    border: 1px solid #CACACA;
}
a.google span{
    font-weight: 500;
    opacity: 0.6;
    color: #232836;
}
@media screen and (max-width: 400px) {
    .form{
        padding: 20px 10px;
    }

}

        </style>

        <script>
             const forms = document.querySelector(".forms"),
      pwShowHide = document.querySelectorAll(".eye-icon"),
      links = document.querySelectorAll(".link");
pwShowHide.forEach(eyeIcon => {
    eyeIcon.addEventListener("click", () => {
        let pwFields = eyeIcon.parentElement.parentElement.querySelectorAll(".password");

        pwFields.forEach(password => {
            if(password.type === "password"){
                password.type = "text";
                eyeIcon.classList.replace("bx-hide", "bx-show");
                return;
            }
            password.type = "password";
            eyeIcon.classList.replace("bx-show", "bx-hide");
        })

    })
})
links.forEach(link => {
    link.addEventListener("click", e => {
       e.preventDefault(); //preventing form submit
       forms.classList.toggle("show-signup");
    })
})
        </script>
<!--        <script src="js/script.js"></script>-->
    </body>
</html>

templates/userauthentication/sign_up.html
<!DOCTYPE html>
{% load static %}
<!-- Coding By CodingNepal - codingnepalweb.com -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- CSS -->

    <!-- Boxicons CSS -->
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

</head>
<body>
<section class="container1 forms">
    <!-- Signup Form -->
    <div class="form signup">
        {% if form.errors %}
            <div class="alert alert-danger">
                <strong>{{form.errors}}</strong>
            </div>
        {% endif %}
        <div class="form-content">
            <header>Signup</header>
            <form action="{% url 'userauthentication:sign_up' %}" method="POST">
                {% csrf_token %}
                <div class="field input-field">
                    {{form.username}}
                </div>
                <div class="field input-field">
                    {{form.email}}
                </div>
                <div class="field input-field">
                    {{form.password1}}
                </div>
                <div class="field input-field">
                    {{form.password2}}
                </div>
                <div style="margin-top:10px;">
                    <input type="radio" name="gender" id="dot-1">
                    <label>I am vendor</label><br>
                    <input type="radio" name="gender" id="dot-2">
                    <label>I am customer</label>
                </div>
                <div class="field button-field">
                    <a href="">
                        <button>Signup</button>
                    </a>
                </div>
            </form>
            <div class="form-link">
                <span>Already have an account? <a href="{% url 'userauthentication:sign_in' %}" class="link login-link">Login</a></span>
            </div>
        </div>
        <div class="line"></div>
        <div class="media-options">
            <a href="#" class="field facebook">
                <i class='bx bxl-facebook facebook-icon'></i>
                <span>Login with Facebook</span>
            </a>
        </div>
        <div class="media-options">
            <a href="#" class="field google">
                <img src="\static\assets\images\icons\google.png" alt="" class="google-img">
                <span>Login with Google</span>
            </a>
        </div>
    </div>
</section>
<style>
    /* Google Fonts - Poppins */
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap');

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
    }

    .container1 {
        height: 900px;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: #e1eaea;
        column-gap: 30px;
    }

    .form {
        position: absolute;
        max-width: 430px;
        width: 100%;
        padding: 30px;
        border-radius: 6px;
        background: #FFF;
    }

    header {
        font-size: 28px;
        font-weight: 600;
        color: #232836;
        text-align: center;
    }

    form {
        margin-top: 30px;
    }

    .form .field {
        position: relative;
        height: 50px;
        width: 100%;
        margin-top: 20px;
        border-radius: 6px;
    }

    .field input,
    .field button {
        height: 100%;
        width: 100%;
        border: none;
        font-size: 16px;
        font-weight: 400;
        border-radius: 6px;
    }

    .field input {
        outline: none;
        padding: 0 15px;
        border: 1px solid #CACACA;
    }

    .field input:focus {
        border-bottom-width: 2px;
    }

    .field button {
        color: #fff;
        background-color: #0171d3;
        transition: all 0.3s ease;
        cursor: pointer;
    }

    .field button:hover {
        background-color: #016dcb;
    }

    .form-link {
        text-align: center;
        margin-top: 10px;
    }

    .form-link span,
    .form-link a {
        font-size: 14px;
        font-weight: 400;
        color: #232836;
    }

    .form a {
        color: #0171d3;
        text-decoration: none;
    }

    .form-content a:hover {
        text-decoration: underline;
    }

    .line {
        position: relative;
        height: 1px;
        width: 100%;
        margin: 36px 0;
        background-color: #d4d4d4;
    }

    .line::before {
        content: 'Or';
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: #FFF;
        color: #8b8b8b;
        padding: 0 15px;
    }

    .media-options a {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    a.facebook {
        color: #fff;
        background-color: #4267b2;
    }

    a.facebook .facebook-icon {
        height: 28px;
        width: 28px;
        color: #0171d3;
        font-size: 20px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: #fff;
    }

    .facebook-icon,
    img.google-img {
        position: absolute;
        top: 50%;
        left: 15px;
        transform: translateY(-50%);
    }

    img.google-img {
        height: 20px;
        width: 20px;
        object-fit: cover;
    }

    a.google {
        border: 1px solid #CACACA;
    }

    a.google span {
        font-weight: 500;
        opacity: 0.6;
        color: #232836;
    }

    @media screen and (max-width: 400px) {
        .form {
            padding: 20px 10px;
        }
    }
</style>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

<!-- JavaScript -->

</body>
</html>